
** Code:
---
-
* Opportunities - Oct 2018
** <2019-03-18 Mon 21:17> OPPORTUNITY: Product Specialist-Fluid Solutions - WATTS
   Date: <2019-03-18 Mon 21:17> 
   Position: Product Specialist-Fluid Solutions
   Payrate:
   Employer name/address/phone/URL: WATTS WATER TECHNOLOGIES 
   Person Contacted: Anna Bengco <anna.bengco@personiv.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-03-18 Mon 19:05> OPPORTUNITY:  MassHire Framingham Colleague 
   Date: <2019-03-18 Mon 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Career Centers
   Person Contacted: Frank Yeoung, Davidson 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Contact maintenance
-

** <2019-03-19 Tue 11:13> OPPORTUNITY: 19-03629-----------Analyst ---------12 Months contract project at Westminster,

    Date: <2019-03-19 Tue 11:13> 
    Position: Analyst
    Payrate:
    Employer name/address/phone/URL: Axelon Services Corporation
    Person Contacted: Mohd. Safi uddin Khan <safi.khan@axelon.com>
    HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
    Results: Additional Follow up requested AFTER presented to client
 -
** <2019-03-19 Tue 21:27> OPPORTUNITY: Technical Support Specialist Opportunity (Windows Upgrade)
   Date: <2019-03-19 Tue 21:27> 
   Position:  Technical Support Specialist 
   Payrate:
   Employer name/address/phone/URL:  TalentBurst, Inc.
   Person Contacted: Roberto Calabrese <roberto.calabrese@talentburst.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-03-20 Wed 08:27> OPPORTUNITY: Fantastic job opportunity for MS Access developer at Boston, MA

Create and provide data analysis solutions using Microsoft Access 2010, 2013 and 2016
    Use external databases to create analysis solutions.
    Create various different reports as required.
    Generate appropriate ad-hoc reporting.
    Strong SQL queries, Stored procedures
    Support access application with SQL Server 2008 backend.



   Date: <2019-03-20 Wed 08:27> 
   Position: MS Access developer 
   Payrate:
   Employer name/address/phone/URL: ApTask 
   Person Contacted: Aravind Vennam <vennam@aptask.com>
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-
** <2019-03-20 Wed 09:07> OPPORTUNITY: Your Application For the Position IT Business Analyst, IS Projects at NATIONAL GRID 
  
   Date: <2019-03-21 Thu 09:07> 
   Position: IT Business Analyst
   Payrate:
   Employer name/address/phone/URL: National Grid
   Person Contacted: National Grid Careers system@successfactors.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-03-20 Wed 21:17> OPPORTUNITY: Product Specialist-Fluid Solutions - WATTS
   Date: <2019-03-20 Wed 21:17> 
   Position: Product Specialist-Fluid Solutions
   Payrate:
   Employer name/address/phone/URL: WATTS WATER TECHNOLOGIES 
   Person Contacted: Anna Bengco <anna.bengco@personiv.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: 2nd Follow up requested after reply
-
** <2019-03-20 Wed 15:47> OPPORTUNITY: looking for a Junior Web Developer in Somerville, MA - Right to Hire position 
   Date: <2019-03-20 Wed 15:47> 
   Position: Junior Web Developer 
   Payrate:
   Employer name/address/phone/URL: Global Technical Talent, Inc.
   Person Contacted: Narendra Singh <nsingh@gttit.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-03-20 Wed 15:52> OPPORTUNITY: URGENT- Contract role for a Windows OS Consultant in Marlborough, MA
   Date: <2019-03-20 Wed 15:52> 
   Position: Windows OS Consultant
   Payrate:
   Employer name/address/phone/URL: GTT, LLC 
   Person Contacted: Anam Ali <aali@gttit.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-03-20 Wed 15:58> OPPORTUNITY: Data Analyst Role Available! #19-03247
   Date: <2019-03-20 Wed 15:58> 
   Position: Data Analyst
   Payrate:
   Employer name/address/phone/URL: Axelon Services Corporation
   Person Contacted: Sunil Kokila sunil.kokila@axelon.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-03-21 Thu 16:13> OPPORTUNITY: IT Business Analyst, IS Projects  
   Date: <2019-03-21 Thu 16:13> 
   Position: IT Business Analyst, IS Projects 
   Payrate: $67k - $96k (Glassdoor est.) 
   Employer name/address/phone/URL: National Grid USA - Waltham, MA 
   Person Contacted:  Glassdoor <noreply@glassdoor.com>
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested submitted application
-
** <2019-03-21 Thu 16:13> OPPORTUNITY: IT Analyst/Programmer   
   Date: <2019-03-21 Thu 16:13> 
   Position: IT Analyst/Programmer  
   Payrate:  
   Employer name/address/phone/URL: GeoLogics - Billerica, MA 
   Person Contacted:  Glassdoor <noreply@glassdoor.com>
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested submitted application
-
** <2019-03-21 Thu 16:13> OPPORTUNITY: New opportunity at Verizon    
   Date: <2019-03-21 Thu 16:13> 
   Position: Systems Analyst  
   Payrate:  
   Employer name/address/phone/URL: Verizon - Lowell, MA
   Person Contacted:  Glassdoor <noreply@glassdoor.com>
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested submitted application
-
** <2019-03-21 Thu 16:31> OPPORTUNITY: Programmer - AllStar Staffing Group - Boston, MA 
   Date: <2019-03-21 Thu 16:31> 
   Position: Programmer - AllStar Staffing Group - Boston, MA 
   Payrate:
   Employer name/address/phone/URL: ZipRecruiter
   Person Contacted: Phil @ ZipRecruiter <phil@ziprecruiter.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested submitted application
-
** <2019-03-21 Thu 16:31> OPPORTUNITY: Systems Administrator - Allied Government Solutions - Burlington, MA 
   Date: <2019-03-21 Thu 16:31> 
   Position: Systems Administrator - Allied Government Solutions - Burlington, MA
   Payrate: $48 - $52 hourly (USD)
   Employer name/address/phone/URL: ZipRecruiter
   Person Contacted: Phil @ ZipRecruiter <phil@ziprecruiter.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested submitted application
-
** <2019-03-21 Thu 19:05> OPPORTUNITY:  MassHire Framingham Colleague 
   Date: <2019-03-21 Thu 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Career Centers
   Person Contacted: Frank Yeoung, Davidson 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Contact maintenance for future meeting
-
** <2019-03-22 Fri 19:05> OPPORTUNITY:  MassHire Framingham Colleague 
   Date: <2019-03-22 Fri 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Career Centers
   Person Contacted: Frank Yeoung, Davidson 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: In Person
   Results: Luncheon Networking meeting in Malden Sun Kong restaurant
-
** <2019-03-22 Fri 19:05> OPPORTUNITY:  MassHire Framingham Career Centers
   Date: <2019-03-22 Fri 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Career Centers
   Person Contacted: Doug Cole <dcole@masshiremsw.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Notification of Jobfair
-
** <2019-03-22 Fri 19:05> OPPORTUNITY:  MassHire Framingham Career Centers
   Date: <2019-03-22 Fri 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Career Centers
   Person Contacted: Ed Lawrence <elawrence@masshiremsw.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Info on salary history questions
-
** <2019-03-22 Fri 10:52> OPPORTUNITY: Windows 10 Administrator Needed! - Worcester, MA 
    Date: <2019-03-22 Fri 10:52> 
    Position: Sr. Windows Administrator - Windows 10 SME
    Payrate:
    Employer name/address/phone/URL: NTT DATA
    Person Contacted: Tiffany Vuong <tiffany.vuong@nttdata.com>
    HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
    Results: Follow up requested 
 -

** <2019-03-22 Fri 16:31> OPPORTUNITY: Programmer - AllStar Staffing Group - Boston, MA 
   Date: <2019-03-22 Fri 16:31> 
   Position: Programmer - AllStar Staffing Group - Boston, MA 
   Payrate:
   Employer name/address/phone/URL: ZipRecruiter
   Person Contacted: Phil @ ZipRecruiter <phil@ziprecruiter.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Informed resume viewed 3 times and recruiter requested contact
-
** <2019-03-16 Sat 17:58> OPPORTUNITY: Tatnuck Booksellers Group 
   Date: <2019-03-16 Sat 17:58> 
   Position: Systems Integrator
   Payrate: $90K/yr
   Employer name/address/phone/URL: Tatnuck Worcester Rd Westboro
   Person Contacted: David Sullivan and Group tatnuck_group@yahoogroups.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Emailed job fair announcement
-
** <2019-03-23 Sat 11:25> OPPORTUNITY: Job Role: SFDC Engineer 
   Date: <2019-03-23 Sat 11:25> 
   Position: SFDC Engineer
   Payrate:
   Employer name/address/phone/URL: Info Way Solutions LLC
   Person Contacted: prabhu Infoway prabhu@Infowaygroup.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

