
** Code:
---
-
* Opportunities Starting April 07, 2019
** <2019-05-13 Mon 13:24> OPPORTUNITY: About City Career Fair: 
   Date: <2019-05-13 Mon 13:24> 
   Position: Software Engineer 
   Payrate:
   Employer name/address/phone/URL: City Career Fair
   Person Contacted: Phil@ziprecruiter .com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Job Closed
-
** <2019-05-13 Mon 16:11> OPPORTUNITY: Software Engineer II
   Date: <2019-05-13 Mon 16:11> 
   Position: Software Engineer II
   Payrate:
   Employer name/address/phone/URL: RetirementJobs.com/Wayfair https://retirementjobs.com/job/software-engineer-ii-boston-massachusetts-15783128
   Person Contacted: anonymous
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: web
   Results: Job Closed
-
** <2019-05-13 Mon 19:05> OPPORTUNITY:  MassHire Framingham Colleague Meeting and Lunch
   Date: <2019-05-13 Mon 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Colleague(s)
   Person Contacted: Frank Yeoung  frankxyeung@gmail.com, David Sullivan Main St Westboro MA
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.:  
   Results: Discuss opportunities
-
** <2019-05-14 Tue 19:05> OPPORTUNITY:  MassHire Framingham Career Centers
   Date: <2019-05-14 Tue 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Career Centers
   Person Contacted: Ed Lawrence elawrence@masshiremsw.com  Worcester Rd Framingham MA
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: in person
   Results: Network Meeting Interview Questions


-
** <2019-05-14 Tue 19:05> OPPORTUNITY:  MassHire Framingham Career Centers
   Date: <2019-05-14 Tue 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Career Centers
   Person Contacted: Doug Cole dcole@masshiremsw.com  Worcester Rd Framingham MA
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: in person
   Results: Responded to Doug and Eric about Examity Lead
-

** <2019-05-14 Tue 21:02> OPPORTUNITY: TECH SUPPORT - $45,000+ for Support Agent (work remotely) 
   Date: <2019-05-14 Tue 21:02> 
   Position: Tech Support
   Payrate: $45,000 to $70,000 Annually
   Employer name/address/phone/URL: Ziprecruiter/theITSC  
   Person Contacted: Phil@Ziprecruiter.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email/web
   Results: Follow up requested Submitted Application
-

** <2019-05-15 Wed 19:05> OPPORTUNITY:  MassHire Framingham Colleague Meeting @ AARP in Worcester and Lunch
   Date: <2019-05-15 Wed 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Colleague(s) at AARP
   Person Contacted: Frank Yeoung  frankxyeung@gmail.com, David Sullivan Brook St Worcester MA
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.:  in person
   Results: Discuss opportunities
-
** <2019-05-16 Thu 19:05> OPPORTUNITY:  MassHire Framingham Career Centers
   Date: <2019-05-16 Thu 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Career Centers
   Person Contacted: Doug Cole dcole@masshiremsw.com  Worcester Rd Framingham MA
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: in person
   Results: Responded to Doug and Eric about Examity Lead and sent Resume
-
** <2019-05-16 Thu 17:58> OPPORTUNITY: Tatnuck Booksellers Group 
   Date: <2019-05-16 Thu 17:58> 
   Position: Systems Integrator
   Payrate: $90K/yr
   Employer name/address/phone/URL: Tatnuck Booksellers Lyman Rd Westboro
   Person Contacted: David Sullivan and Group tatnuck_group@yahoogroups.com Lyman Westboro MA
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: In person
   Results: Status  and branding workshop.
-
** <2019-05-17 Fri 19:05> OPPORTUNITY:  MassHire Framingham Colleague Meeting 
   Date: <2019-05-17 Fri 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Colleague(s)
   Person Contacted: Frank Yeoung  frankxyeung@gmail.com, David Sullivan Brook St Worcester MA
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email & virtual 
   Results: Discuss opportunities
-
** <2019-05-17 Fri 21:02> OPPORTUNITY: TECH SUPPORT - $45,000+ for Support Agent (work remotely) 
   Date: <2019-05-17 Fri 21:02> 
   Position: Tech Support
   Payrate: $45,000 to $70,000 Annually
   Employer name/address/phone/URL: Ziprecruiter/theITSC  
   Person Contacted: Phil@Ziprecruiter.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email/web
   Results: Follow up requested Submitted Application (2nd Application)
-

** <2019-05-17 Fri 17:44> OPPORTUNITY: Hubspot instance that they would like to integrate with a separate department's Salesforce instance. 
   Date: <2019-05-17 Fri 17:44> 
   Position: Hubspot Integration Consultant
   Payrate:
   Employer name/address/phone/URL: Mondo
   Person Contacted: Carter Lowe carter.lowe@mondo.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results:  Follow up requested 
-

** <2019-05-17 Fri 17:54> OPPORTUNITY: Excellent opportunity for Automation Engineer at Boston, MA 
   Date: <2019-05-17 Fri 17:54> 
   Position: Automation Engineer
   Payrate:  $75/hr on C2C and 1099 and $65/hr on W2
   Employer name/address/phone/URL: SOTOCU
   Person Contacted: Ravi Sharma <ravi@sotocu.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-05-17 Fri 18:10> OPPORTUNITY: Urgently Required SQL DBA in Boston, MA 
   Date: <2019-05-17 Fri 18:10> 
   Position:  SQL DBA
   Payrate:
   Employer name/address/phone/URL: http://www.net2source.com/
   Person Contacted: Clifford Daniels <clifford@net2source.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-
** <2019-05-17 Fri 21:56> OPPORTUNITY: LinkedIN
   Date: <2019-05-17 Fri 21:56>
   Position: Systems Integrator VAR
   Payrate: $90K/yr
   Employer name/address/phone/URL: http://www.linkedin.com
   Person Contacted: Pierre Moody Manager Tech Staffing Complete Staffing Solutions 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: web
   Results: Connected and has lead
-
** <2019-05-17 Fri 21:56> OPPORTUNITY: LinkedIN
   Date: <2019-05-17 Fri 21:56>
   Position: Systems Integrator VAR
   Payrate: $90K/yr
   Employer name/address/phone/URL: http://www.linkedin.com
   Person Contacted: Pat Martin Graphic Designer
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: web
   Results: Connected 
-

** <2019-05-18 Sat 08:56> OPPORTUNITY: Lead DevOps Opening- Boston, MA- Full-Time 
   Date: <2019-05-18 Sat 08:56> 
   Position: DevOps Engineer 
   Payrate:
   Employer name/address/phone/URL: Huxley IT
   Person Contacted: Eric Morra e.morra@huxley.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-05-18 Sat 12:36> OPPORTUNITY: Full Time Role | Senior Data Engineer | Westboro, MA
   Date: <2019-05-18 Sat 12:36> 
   Position: Senior Data Engineer 
   Payrate:
   Employer name/address/phone/URL: http://email.bullhorn.com/
   Person Contacted: Amy Borkar via bullhornmail.com 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email 
   Results: Follow-up requested
-

** <2019-05-18 Sat 12:41> OPPORTUNITY: Urgent Job: Need Sr. Marketing Communications Specialist in Tewksbury, MA 01876
   Date: <2019-05-18 Sat 12:41> 
   Position: Sr. Marketing Communications Specialist
   Payrate:
   Employer name/address/phone/URL: VARITE
   Person Contacted: Amit Rai <Amit.Rai@varite.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow-up requested
-

** <2019-05-18 Sat 15:47> OPPORTUNITY: Re: We are looking for Application Administrator at Kent, Washington

   Date: <2019-05-18 Sat 15:47> 
   Position: Application Administrator
   Payrate:
   Employer name/address/phone/URL: Monster www.Monster.com
   Person Contacted: Sandeep
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: web
   Results: Follow-up requested


