
** Code:
---
-
* Opportunities Starting April 07, 2019
** <2019-05-05 Sun 15:51> OPPORTUNITY: Database Engineer (big data) position with one of the largest independent AI companies in the...
   Date: <2019-05-05 Sun 15:51> 
   Position: Database Engineer
   Payrate:
   Employer name/address/phone/URL: Interactions
   Person Contacted: Michael Goodwin https://www.linkedin.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: web
   Results: Follow up requested
-

** <2019-05-05 Sun 22:28> OPPORTUNITY: Urgent need :: DB2 Database Administrator :: Remote + Travel :: 9+ exp Immediate Interview
   Date: <2019-05-05 Sun 22:28> 
   Position: DB2 Database Administrator
   Payrate:
   Employer name/address/phone/URL: http://www.rsrit.com/
   Person Contacted: Saikumar Rudharraju saikumar.r@rsrit.com via mailgun.org 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-05-05 Sun 22:37> OPPORTUNITY: Hubspot (wordpress/php) Developer - Boston, MA (Onsite Contract)
   Date: <2019-05-05 Sun 22:37> 
   Position: Hubspot Developer and Implementation Specialist (Contractor Role) 
   Payrate:
   Employer name/address/phone/URL: Lenmar Consulting Inc  (a Kellton Tech Company)
   Person Contacted: Valerian-Lenmar <vdcunha@lenmarit.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested 
-
** <2019-05-05 Sun 22:37> OPPORTUNITY: Hubspot (wordpress/php) Developer - Boston, MA (Onsite Contract)
   Date: <2019-05-05 Sun 22:45> 
   Position: Hubspot Developer and Implementation Specialist (Contractor Role) 
   Payrate:
   Employer name/address/phone/URL: Global Technical Talent, Inc
   Person Contacted:  Paula Bryant <pbryant@gttit.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested 
-

** <2019-05-05 Sun 00:00> OPPORTUNITY: Lifepoints Online Survey Taker 
   Date: <2019-05-05 Sun 00:00> 
   Position: Survey Taker
   Payrate: Lifepoints
   Employer name/address/phone/URL: http://www.lifepoints.com and SnagaJob.com
   Person Contacted: Anonymous
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: web
   Results: Submitted application
-

** <2019-05-06 Mon 09:56> OPPORTUNITY: I want you on my team
   Date: <2019-05-06 Mon 09:56> 
   Position: Reviewer
   Payrate: Free Books
   Employer name/address/phone/URL: "Street Team,"
   Person Contacted: Damon Zahariades via m.convertkit.com  damon@artofproductivity.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-
** <2019-05-06 Mon 21:56> OPPORTUNITY: LinkedIN
   Date: <2019-05-06 Mon 21:56>
   Position: Systems Integrator VAR
   Payrate: $90K/yr
   Employer name/address/phone/URL: http://www.linkedin.com
   Person Contacted: Brian Long Recruiter 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: web
   Results: Connected 
-

** <2019-05-06 Mon 22:50> OPPORTUNITY: DevOps Engineer Opening- Boston, MA- Full-Time Permanent
   Date: <2019-05-06 Mon 22:50> 
   Position: DevOps Engineer
   Payrate:
   Employer name/address/phone/URL: Huxley IT
   Person Contacted: Eric Morra e.morra@huxley.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-05-06 Mon 22:54> OPPORTUNITY: Contract to hire - Cloud Infrastructure Engineer, Boston, MA
   Date: <2019-05-06 Mon 22:54> 
   Position: Cloud Infrastructure Engineer
   Payrate:
   Employer name/address/phone/URL: https://www.xoriant.com/
   Person Contacted: Avinash Patil <Avinash.Patil@xoriant.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email 
   Results: Follow up requested
-

** <2019-05-06 Mon 22:58> OPPORTUNITY: Looking for a Jr. Content/Curriculum Developer in Worcester, MA
   Date: <2019-05-06 Mon 22:58> 
   Position: Jr. Content/Curriculum Developer
   Payrate:
   Employer name/address/phone/URL: http://www.gttit.com/
   Person Contacted: Narendra Singh nsingh@gttit.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-05-06 Mon 23:05> OPPORTUNITY: Solaris/Redhat IT Transition Engineer-Job Opening Marlborough, MA
   Date: <2019-05-06 Mon 23:05> 
   Position:  SOLARIS/REDHAT IT TRANSITION Engr.
   Payrate:
   Employer name/address/phone/URL: http://www.pdstech.com/
   Person Contacted: Sana Khan <skhan@pdstech.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-05-06 Mon 23:08> OPPORTUNITY: Job opening of a Document Control Coordinator_Tewksbury, Massachusetts 01876
   Date: <2019-05-06 Mon 23:08> 
   Position: Document Control Coordinator
   Payrate:
   Employer name/address/phone/URL: http://www.ustechsolutions.com/
   Person Contacted: Kiran Kumar Saxena <kirans@ustechsolutionsinc.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-05-07 Tue 21:56> OPPORTUNITY: LinkedIN
   Date: <2019-05-07 Tue 21:56>
   Position: Systems Integrator VAR
   Payrate: $90K/yr
   Employer name/address/phone/URL: http://www.linkedin.com
   Person Contacted: Yeswanth Kumar Recruiter 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: web
   Results: Connected 
-

** <2019-05-07 Tue 19:05> OPPORTUNITY:  MassHire Framingham Career Centers
   Date: <2019-05-07 Tue 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Career Centers
   Person Contacted: Jamie and Ed Lawrence elawrence@masshiremsw.com  Worcester Rd Framingham MA
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: in person
   Results: Career Center RESEA meeting with Jamie and Ed Lawrence


-
** <2019-05-08 Wed 21:56> OPPORTUNITY: LinkedIN
   Date: <2019-05-08 Wed 21:56>
   Position: Systems Integrator VAR
   Payrate: $90K/yr
   Employer name/address/phone/URL: http://www.linkedin.com
   Person Contacted: Balakrisnan Modur Deployment Engineer
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: web
   Results: Connected 
-
** <2019-05-08 Wed 19:05> OPPORTUNITY:  MassHire Framingham Colleague Meeting and Lunch
   Date: <2019-05-08 Wed 19:05>
   Position: SQL Server DBA
   Payrate: $90K
   Employer name/address/phone/URL: MassHire Framingham Colleague(s)
   Person Contacted: Frank Yeoung  frankxyeung@gmail.com, David Sullivan Main St Westboro MA
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.:  
   Results: Discuss opportunities
-

** <2019-05-09 Thu 20:48> OPPORTUNITY: Urgent contract role for Developer in Boston MA. 
   Date: <2019-05-09 Thu 20:48> 
   Position: Developer
   Payrate:
   Employer name/address/phone/URL: Javen Technologies, Inc. 
   Person Contacted: Surbhi Singh <surbhi@javentechnologies.com> 
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-
** <2019-05-09 Thu 07:25> OPPORTUNITY:  Posted on ZipRecruiter AS400 Programmer Analyst - Contract - Boston, MA 
   Date: <2019-05-09 Thu 07:25> 
   Position: AS400 Programmer Analyst
   Payrate:
   Employer name/address/phone/URL: Ziprecruiter 
   Person Contacted: Team@Ziprecruiter.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested informed application was viewed
-
** <2019-05-10 Fri 07:25> OPPORTUNITY:  Posted on ZipRecruiter AS400 Programmer Analyst - Contract - Boston, MA 
   Date: <2019-05-10 Fri 07:25> 
   Position: AS400 Programmer Analyst
   Payrate:
   Employer name/address/phone/URL: Ziprecruiter 
   Person Contacted: Team@Ziprecruiter.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Informed by ZipRecruiter Job Closed
-
** <2019-05-10 Fri 07:25> OPPORTUNITY:    Posted on ZipRecruiter IT Support Engineer (Part Time) 
   Date: <2019-05-10 Fri 07:25> 
   Position: IT Support Engineer (Part Time)
   Payrate:
   Employer name/address/phone/URL: Ziprecruiter 
   Person Contacted: Phil@Ziprecruiter.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Submitted application
-
** <2019-05-11 Sat 06:50> OPPORTUNITY: Re: BondLink opportunity referred by ZipRecruiter
   Date: <2019-05-11 Sat 06:50> 
   Position:  IT Support Engineer (Part Time) 
   Payrate:
   Employer name/address/phone/URL: BondLink
   Person Contacted: Kristin Patrick <candidate-0ca890b566e2@bondlink.breezy-mail.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested
-

** <2019-05-11 Sat 11:32> OPPORTUNITY: Re: MIT-Lincoln Labs / IT System Administrator I - ITSYS04767
   Date: <2019-05-11 Sat 11:32> 
   Position: IT System Administrator
   Payrate:
   Employer name/address/phone/URL: Monster 
   Person Contacted: Amarjeet Savant https://www.monster.com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: web
   Results: Follow up requested
-

** <2019-05-11 Sat 13:24> OPPORTUNITY: About City Career Fair: 
   Date: <2019-05-11 Sat 13:24> 
   Position: Software Engineer 
   Payrate:
   Employer name/address/phone/URL: City Career Fair
   Person Contacted: Phil@ziprecruiter .com
   HOW CONTACTED - Web, phone, mail, job fair, networking, etc.: email
   Results: Follow up requested Submitted Application
-

